---
# Copyright 2018 (c), OpenNext SAS.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cobbler_distros:
  - distro_name: CentOS-7
    device_or_iso_path: /var/tmp/isos/CentOS-7-x86_64-DVD-1810.iso
    arch: x86_64

cobbler_profiles:
  - profile_name: Infra-CentOS-7-x86_64
    distro: CentOS-7-x86_64
    kickstart_file_name: centos7-osa_infra-sda.ks
  - profile_name: Ceph-CentOS-7-x86_64
    distro: CentOS-7-x86_64
    kickstart_file_name: centos7-osa_ceph-sda.ks
  - profile_name: Compute-CentOS-7-x86_64
    distro: CentOS-7-x86_64
    kickstart_file_name: centos7-osa_compute-sda.ks
  - profile_name: Default-CentOS-7-x86_64
    distro: CentOS-7-x86_64
    kickstart_file_name: centos7-osa_default-sda.ks
  - profile_name: Storage-CentOS-7-x86_64
    distro: CentOS-7-x86_64
    kickstart_file_name: centos7-osa_storage-sda.ks
  - profile_name: Swift-CentOS-7-x86_64
    distro: CentOS-7-x86_64
    kickstart_file_name: centos7-osa_swift-sda.ks
    
    