---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

onpc_openstack_release: 18.1.0
onpc_openstack_branch: "stable/rocky"
onpc_lma_release: master
onpc_bootstrap_scenario: "{{ lookup('env','SCENARIO') | default('onpc', true) }}"
onpc_bootstrap_config_path: /opt/onpc-bootstrap/etc/openstack_deploy
onpc_install_method: "{{ lookup('env', 'INSTALL_METHOD') | default('source', true)  }}"
onpc_debug_enabled: false
onpc_low_end_profile: false
onpc_cpu_overcommit: 8.0
onpc_dhcp_domain: opennext.local
onpc_region_controller: maas
# The variable onpc_environment_name is used to tag the monitoring metrics
# and alerts.
onpc_environment_name: "{{ environment_name | default(onpc_dhcp_domain, true) }}"
onpc_run_tempest_tests: no
onpc_mandatory_roles:
    - compute
    - storage
    - network
    - logging
    - monitoring

onpc_host_data_disk_device: sda2

# The proxy is the deployment host when it is configured as the default
# gateway for the machines it manages. The proxy should work transparently
# on TCP port (default 3128). Otherwise machines will need to access the
# proxy on a specific host and port.
#
# proxy_host: "{{ onpc_region_controller }}.{{ onpc_dhcp_domaine }}"
# proxy_port: "3128"

# Note: MAAS provides an internal proxy server.
# The proxy is the deployment host where MAAS is configured as the default
# gateway for the machines it manages.  If the region controller is configured in MAAS as
# the default gateway for the machines it manages then the proxy will work transparently
# (on TCP port 3128). Otherwise machines will need to access it on TCP port 8000.
#
# proxy_env_url: "http:/{{ onpc_region_controller }}.{{ onpc_dhcp_domain }}:8000/"
# onpc_proxy_environment:
#   http_proxy: "{{ proxy_env_url }}"
#   https_proxy: "{{ proxy_env_url }}"
#   no_proxy: "localhost,127.0.0.1"