---
# Copyright (c) 2019, Patrick Petit <patrick.michel.petit@gmail.com>

#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# management_network: used to provide access the internal services and containers
# tunnel_network: used by tenants private networks 
# storage_network: used by the storage services (optional)
# external_network: used to provide access from external (Internet) network
# lbaas_network: used by tenants for load balacing (octavia)

# Adjust as per your environment to include any IP addresses that are already used by existing
# physical hosts in the environment where OpenStack will be deployed (and ensuring that you've
# included any reserved IP addresses for physical growth too). Single IP addresses or ranges
# (start and end placed either side of a ',') can be placed under the 'reserved' stanza for each # OSA network.

management_network: 172.29.236.0/22
tunnel_network: 172.29.240.0/22
storage_network: 172.29.244.0/22
external_network: 172.29.248.0/22
api_network: 192.168.1.0/24

management_interface: br-mgmt
tunnel_interface: br-vxlan
storage_interface: br-storage
external_interface: br-vlan
api_interface: br-api

external_vip_addr: 192.168.1.100
internal_vip_addr: 172.29.236.100
default_gateway_addr: 172.29.236.1

osa_provider_networks:
  - name: management
    cidr: "{{ management_network }}"
    interface: "{{ management_interface }}"
    reserved:
      - "172.29.236.1,172.29.236.50"
      - "172.29.236.100"
  - name: tunnel
    cidr: "{{ tunnel_network }}"
    interface: "{{ tunnel_interface }}"
    reserved:
      - "172.29.240.1,172.29.240.50"
      - "172.29.240.100"
    roles: ['network', 'compute']
  - name: storage
    cidr: "{{ storage_network }}"
    interface: "{{ storage_interface }}"
    reserved:
      - "172.29.244.1,172.29.244.50"
      - "172.29.244.100"
    roles: ['storage', 'compute', 'ceph']
  - name: external
    cidr: "{{ external_network }}"
    interface: "{{ external_interface }}"
    reserved:
      - "172.29.248.1,172.29.248.50"
      - "172.29.248.100"
    roles: ['network', 'compute']
  
