# OpenNext Nginx reverse proxy configuration
---
# Copyright (c) 2019, Patrick Petit <patrick.michel.petit@gmail.com>

#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## The installation and configuration of Nginx as a reverse proxy
#  to access OpenNext services UIs (ex. Horizon, Grafana, Kibana, ...).
reverse_nginx_enabled: "{{ opennext_reverse_nginx | default(false) | bool }}"

nginx_remove_default_vhost: true

nginx_vhosts:
  - listen: "{{ onpc_reverse_proxy_vip }}:80"
    server_name: "{{ onpc_reverse_proxy_fqdn }} {{ onpc_reverse_proxy_vip }}"
    error_page: ""
    access_log: "/var/log/nginx/openstack_access.log"
    error_log: "/var/log/nginx/openstack_error.log"
    state: "present"
    template: "../etc/nginx/template/vhost.j2"
    filename: "openstack.conf"
    locations:
      - path: /
        content: |
          return 302 https://$host$request_uri;

  - listen: "172.30.0.200:443 ssl"
    server_name: "horizon.ewc.meteo.fr 172.30.0.200"
    error_page: ""
    access_log: ""
    error_log: ""
    state: "present"
    template: "../etc/nginx/template/vhost.j2"
    filename: "openstack_ssl.conf"
    locations:
      - path: /horizon
        content: |
          proxy_pass http://192.168.0.200;
          proxy_request_buffering off;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_set_header Origin http://$host;
          proxy_set_header Accept-Encoding "";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_connect_timeout 90;
          proxy_send_timeout 90;
          proxy_read_timeout 90;
      - path: /nova
        content: |
            proxy_pass http://{{  }}

nginx_extra_http_options: |
  proxy_buffering    off;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Scheme $scheme;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   Host $http_host;