---
# This file contains data that controls the post-deployment configuration
# of OpenStack by the Ansible playbook openstack-service-setup.yml

# Define a set of VM flavors to be created
vm_flavors:
  - name: m1.micro
    ram: 256
    vcpus: 1
    disk: 1
    swap: 0
    ephemeral: 0
  - name: m1.tiny
    ram: 512
    vcpus: 1
    disk: 1
    swap: 0
    ephemeral: 0
  - name: m1.mini
    ram: 1024
    vcpus: 2
    disk: 10
    swap: 512
    ephemeral: 0
  - name: m1.small
    ram: 2048
    vcpus: 3
    disk: 20
    swap: 1024
    ephemeral: 4
  - name: m1.medium
    ram: 4096
    vcpus: 6
    disk: 60
    swap: 2048
    ephemeral: 20
  - name: m1.large
    ram: 8192
    vcpus: 12
    disk: 60
    swap: 4096
    ephemeral: 150
  - name: m1.xlarge
    ram: 16384
    vcpus: 24
    disk: 600
    swap: 8192
  - name: m1.heavy
    ram: 32768
    vcpus: 48
    disk: 60
    swap: 8192

# Create shared networks and subnets:
provider_net_name: PROVIDER_NETWORK
provider_net_cidr: "{{ external_network }}"
provider_dns_servers: "{{ provider_network_dns_servers | default(['8.8.8.8', '8.8.4.4']) }}"
provider_subnet_name: "{{ provider_net_name }}_SUBNET"

private_net_name: TENANT_NETWORK
private_net_cidr: 192.168.0.0/24
private_subnet_name: "{{ private_net_name }}_SUBNET"

networks:
  - name: "{{ provider_net_name }}"
    shared: false
    external: true
    network_type: vlan
    physical_network: "{{ external_interface }}"
    segmentation_id: 101
  - name: "{{ private_net_name }}"
    shared: true
    external: false
    network_type: vxlan
    segmentation_id: 101

subnets:
  - name: "{{ provider_subnet_name }}"
    network_name: "{{ provider_net_name }}"
    ip_version: 4
    cidr: "{{ provider_net_cidr }}"
    gateway_ip: "{{ provider_net_cidr | ipaddr('1') | ipaddr('address') }}"
    enable_dhcp: "{{ enable_provider_net_dhcp | default(true) | bool }}"
    allocation_pool_start: "{{ provider_net_cidr | ipaddr('3') | ipaddr('address') }}"
    allocation_pool_end:   "{{ provider_net_cidr | ipaddr('254') | ipaddr('address') }}"
    dns_nameservers: "{{ provider_dns_servers }}"
  - name: "{{ private_subnet_name }}"
    network_name: "{{ private_net_name }}"
    ip_version: 4
    cidr: "{{ private_net_cidr }}"
    gateway_ip: "{{ private_net_cidr | ipaddr('1') | ipaddr('address') }}"
    enable_dhcp: true
    allocation_pool_start: "{{ private_net_cidr | ipaddr('3') | ipaddr('address') }}"
    allocation_pool_end:   "{{ private_net_cidr | ipaddr('254') | ipaddr('address') }}"

router_name: PROVIDER_GATEWAY_ROUTER
security_group_name: PROVIDER_GATEWAY_SECGROUP
port_name: gateway_port

# Neutron security group setup
security_group_rules:
  - name: Allow ICMP
    protocol: icmp
    direction: ingress
  - name: Allow all TCP
    protocol: tcp
    direction: ingress
    port_min: 1
    port_max: 65535
  - name: Allow all UDP
    protocol: udp
    direction: ingress
    port_min: 1
    port_max: 65535

# Create some default images
images:
  - name: Cirros-0.4.0
    format: qcow2
    url: http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
  - name: Ubuntu 18.04 LTS
    format: qcow2
    url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
  - name: Ubuntu 16.04 LTS
    format: qcow2
    url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
  - name: Fedora 31
    format: qcow2
    url: https://download.fedoraproject.org/pub/fedora/linux/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.qcow2
  - name: CentOS 7
    format: qcow2
    url: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
  - name: OpenSuse Leap 15.2
    format: qcow2
    url: https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.2/images/openSUSE-Leap-15.2-OpenStack.x86_64.qcow2
  - name: OpenSuse Leap 42.3
    format: qcow2
    url: https://download.opensuse.org/repositories/Cloud:/Images:/Leap_42.3/images/openSUSE-Leap-42.3-OpenStack.x86_64.qcow2
  - name: Debian 9 Latest
    format: qcow2
    url: https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2
  - name: Debian 10 Latest
    format: qcow2
    url: https://cdimage.debian.org/cdimage/openstack/current-10/debian-10-openstack-amd64.qcow2
