---
# Copyright (c) 2019, Patrick Petit <patrick.michel.petit@gmail.com>

#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- fail:
    msg: "Wrong network specification"
  when: (network is not defined
         or not network.get('cidr')
         or not network.get('interface'))
  tags: check-osa-networks

- name: Set network roles fact
  set_fact:
    network_roles: "{{ network.get('roles', []) }}"
  tags: check-osa-networks

- name: Set interface name
  set_fact:
    interface_name: "{{ network.get('interface')  | replace('-', '_') }}"
  tags: check-osa-networks

- name: "Set network interface '{{ interface_name }}' fact"
  set_fact:
    network_interface: "{{ hostvars[inventory_hostname]['ansible_' + interface_name] | default({}) }}"
  tags: check-osa-networks

- name: "Assert that interface '{{ interface_name }}' exists"
  assert:
    that:
      - network_interface is defined and network_interface | length > 0
    msg: "Interface '{{ interface_name }}' doesn't exists"
  when:
    - ('all' in network_roles) or (network_roles | intersect(host_roles) | length > 0)
  tags: check-osa-networks

- name: "Set interface '{{ interface_name }}' active state fact"
  set_fact:
    active_state: "{{ network_interface['active'] | default(False) }}"
  when:
    - ('all' in network_roles) or (network_roles | intersect(host_roles) | length > 0)
  tags: check-osa-networks

- name: "Assert interface '{{ interface_name }}' state"
  assert:
    that: active_state | bool
    msg: "Interface '{{ interface_name }}' is not active"
  when:
    - ('all' in network_roles) or (network_roles | intersect(host_roles) | length > 0)
  tags: check-osa-networks

- name: "Set interface '{{ interface_name }}' type"
  set_fact:
    interface_type: "{{ network_interface['type'] | default('') }}"
  when:
    - ('all' in network_roles) or (network_roles | intersect(host_roles) | length > 0)
  tags: check-osa-networks

- name: "Assert that the interface '{{ interface_name }}' is a bridge"
  assert:
    that: interface_type == 'bridge'
    msg: "The interface type '{{ interface_type }}' must be 'bridge' }}'"
  when:
    - ('all' in network_roles) or (network_roles | intersect(host_roles) | length > 0)
  tags: check-osa-networks

- name: "Set interface '{{ interface_name }}' IP address fact"
  set_fact:
    interface_address: "{{ network_interface['ipv4']['address'] }}"
  when:
    - ('all' in network_roles) or (network_roles | intersect(host_roles) | length > 0)
    - interface_name != (external_interface | replace('-', '_'))
  tags: check-osa-networks

- name: "Assert that the interface '{{ interface_name }}' has a valid IP address"
  assert:
    that:
      - interface_address | ipaddr(network.get('cidr')) | length > 0
    msg: "The address '{{ interface_address }}' must be  within range '{{ network.get('cidr') }}'"
  when:
    - ('all' in network_roles) or (network_roles | intersect(host_roles) | length > 0)
    - interface_name != (external_interface | replace('-', '_'))
  tags: check-osa-networks