---
- name: Download disk image image file
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/os_image_{{ item.name }}"
    timeout: 600   # big files might take a while to download
  register: download_result
  until: download_result is succeeded
  retries: 10
  delay: 15
  failed_when: download_result is failure
  tags: create-images

- name: "Create disk image '{{ item.name }}'"
  os_image:
    endpoint_type: internal
    cloud: default
    state: present
    is_public: true
    name: "{{ item.name }}"
    filename: "/tmp/os_image_{{ item.name }}"
    disk_format: "{{ item.format }}"
    properties:
      hw_scsi_model: virtio-scsi
      hw_disk_bus: scsi
      hw_qemu_guest_agent: yes
      os_require_quiesce: yes
  tags: create-images

- name: Clean up temp file
  file:
    path: "/tmp/os_image_{{ item.name }}"
    state: absent
  tags: create-images


