---
- name: "Create security group '{{ security_group_name }}'"
  os_security_group:
    cloud: default
    interface: internal
    state: present
    name: "{{ security_group_name }}"
  tags: create-security-groups

- name: Create a security group rule for ping
  os_security_group_rule:
    cloud: default
    interface: internal
    security_group: "{{ security_group_name }}"
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0
  tags: create-security-groups

- name: Create a security group rule for ssh
  os_security_group_rule:
    interface: internal
    cloud: default
    security_group: "{{ security_group_name }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  tags: create-security-groups