---
# Copyright (c) 2019, Patrick Petit <patrick.michel.petit@gmail.com>

#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set profile_roles fact
  set_fact:
    profile_roles: "{{ (item.value.roles | intersect(infra_group)) | ternary((item.value.roles + ['infra']) | unique | list, item.value.roles | unique | list) }}"
  vars:
    infra_group: ['controller', 'network', 'haproxy', 'image']
  tags: always

- name: "Add cobbler profile '{{ profile_name }}'"
  command: >
    cobbler profile add
      --name={{ profile_name }}
      --comment="{{ item.value.comment }}"
      --distro={{ item.value.distro_name | lower }}
      --kickstart=/var/lib/cobbler/kickstarts/{{ item.value.kickstart_file }}
      --name-servers="{{ item.value.name_servers | join(' ') }}"
      --name-servers-search="{{ item.value.name_servers_search | join(' ') | lower }}"
      --mgmt-classes="{{ profile_roles | join(' ') | lower }}"
      --ksmeta="{{ item.value.metadata | join(' ') | lower }}"
  when: profile_name not in registered_profiles
  tags: register-cobbler-profiles

- name: "Edit cobbler profile '{{profile_name}}'" 
  command: >
    cobbler profile edit 
      --name={{ profile_name }}
      --comment="{{ item.value.comment }}"
      --distro={{ item.value.distro_name | lower }}
      --kickstart=/var/lib/cobbler/kickstarts/{{ item.value.kickstart_file }}
      --name-servers="{{ item.value.name_servers | join(' ') }}"
      --name-servers-search="{{ item.value.name_servers_search | join(' ') | lower }}"
      --mgmt-classes="{{ profile_roles | join(' ') | lower }}"
      --ksmeta="{{ item.value.metadata | join(' ') | lower }}"
  when: profile_name in registered_profiles
  tags: register-cobbler-profiles
