---
# Copyright (c) 2019, Patrick Petit <patrick.michel.petit@gmail.com>

#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set system_roles fact
  set_fact:
    system_roles: "{{ (item.value.roles | intersect(infra_group)) | ternary((item.value.roles + ['infra']) | unique | list, item.value.roles | unique | list) }}"
  vars:
    infra_group: ['controller', 'network', 'haproxy', 'image']
  tags: always

- name: "Add cobbler system '{{ system_name }}'"
  command: >
    cobbler system add
      --name="{{ system_name }}"
      --hostname="{{ item.hostname }}"
      --gateway="{{ item.gateway }}"
      --profile="{{ item.profile | lower }}"
      --comment="{{ item.comment | default('') }}"
      --netboot-enabled="{{ item.netboot }}"
      --mgmt-classes="{{ system_roles | join(' ') | lower }}"
      --name-servers="{{ item.name_servers | default([]) | join(' ') }}"
      --name-servers-search="{{ item.name_servers_search | default([]) | join(' ') | lower }}"
  when:
    - system_name not in registered_systems
    - item.state == "present"
  tags: register-cobbler-systems

- name: "Edit cobbler system '{{ item.value.name }}'"
  command: >
    cobbler system edit
      --name="{{ system_name }}"
      --hostname="{{ item.hostname }}"
      --gateway="{{ item.gateway }}"
      --profile="{{ item.profile | lower }}"
      --comment="{{ item.comment | default('') }}"
      --netboot-enabled="{{ item.netboot }}"
      --mgmt-classes="{{ system_roles | join(' ') | lower }}"
      --name-servers="{{ item.name_servers | default([]) | join(' ') }}"
      --name-servers-search="{{ item.name_servers_search | default([]) | join(' ') | lower }}"
  when:
    - system_name in registered_systems
    - item.state == "present"
  tags: register-cobbler-systems

- name: "Delete cobbler system '{{ item.value.name }}'"
  command: >
    cobbler system remove
      --name={{ system_name }}
  when:
    - system_name in registered_systems
    - item.state == "absent"
  tags: register-cobbler-systems

- name: Set system_interfaces_list fact
  set_fact:
    system_interfaces_list: >-
      {%- set sel = [] %}
      {%- for val in onpc_netboot_profiles[item.profile]['interfaces'] %}
      {%-   set interface = val %}
      {%-   if val.assign_mac is defined and val.assign_mac is sameas true %}
      {%-     set _ = interface.update({'mac_address': item['interfaces'][val.label]['mac_address']}) %}
      {%-    endif %}
      {%-   if val.assign_ip is defined and val.assign_ip is sameas true %}
      {%-     set _ = interface.update({'ip_address': item['interfaces'][val.label]['ip_address']}) %}
      {%-   endif %}
      {%-   set _ = sel.append(interface) %}
      {%- endfor %}
      {{- sel | list }}
  tags:
    - register-cobbler-systems
    - register-cobbler-interfaces

-  include: tasks/register-cobbler-interface.yml
   when:
    - item.state == "present"
   loop: "{{ system_interfaces_list }}"
   loop_control:
     loop_var: interface
