---
# Copyright 2019 (c), Patrick Petit.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Get cobbler systems 
  command: >
    cobbler system list
  register: result
  failed_when: result.failed == true
  tags: always 

- name: Set registered_systems fact
  set_facts:
    registered_systems: "{{ result.stdout_lines | map('trim') | list | default([]) }}"
  tags: always

- name: "Register system interface '{{ interface.interface }}'"
  command: >
    cobbler system edit
      --name="{{ system_name }}"
      --interface="{{ interface.interface }}"
      --interface-type="{{ interface.interface_type | default('') }}"
      --interface-master="{{ interface.interface_master | default('') }}"
      --ip-address="{{ interface.ip_address | default('') }}"
      --if-gateway="{{ interface.if_gateway | default('') }}" 
      --mac-address="{{ interface.mac_address | default('') }}"
      --static="{{ interface.static | default('') }}" 
      --bonding-opts="{{ interface.bondig_opts | default('') }}" 
      --bridge-opts="{{ interface.bridge_opts | default('') }}" 
      --dns-name="{{ interface.dns_name | default('') }}"
      --management="{{ interface.management | default(False) }}" 
      --netmask="{{ interface.netmask | default('') }}" 
      --static-routes="{{ interface.static_routes | default([]) | join(' ') }}" 
  when:
    - system_name in registered_systems
  register: result
  failed_when: result.failed == true
  tags:
    - register-cobbler-systems
    - register-cobbler-interfaces

