---
# Copyright (c) 2019, Patrick Petit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Get cobbler distros
  command: >
    cobbler distro list
  register: result
  tags: always

- name: Set registered_distros facts
  set_fact:
    registered_distros: "{{ result.stdout_lines | map('trim') | list | default([]) }}"
    distro_name: "{{ item.distro_name | lower }}-{{ item.arch | lower }}"
  tags: always

- name: Mount device or iso to mount point
  mount: name=/mnt/{{ item.distro_name }}
         src={{ item.device_or_iso_path }}
         opts=ro fstype=iso9660 state=mounted
  when: "distro_name not in registered_distros"
  tags: import-cobbler-distros

- name: "Import cobbler distro '{{item.distro_name}}'"
  command: >
    cobbler import
      --name={{ item.distro_name | lower }}
      --arch={{ item.arch | lower}}
      --path=/mnt/{{ item.distro_name }}
  when: "distro_name not in registered_distros"
  tags: import-cobbler-distros