---
- name: import distros to cobbler
  shell: >-
    cobbler profile
      --name={{ item.distro_name }}
      --distro={{ item.arch }}
      --kickstart=/var/lib/cobbler/kickstarts/{{ item.kickstart_file_name }}
  ignore_errors: true

- name: Sync Cobbler database
  cobbler_sync:
    host: localhost
    username: "{{ cobbler_user.name }}"
    password: "{{ cobbler_user.password }}"
    use_ssl: False
  run_once: yes
