---
# Copyright (c) 2019, Patrick Petit <patrick.michel.petit@gmail.com>

#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set onpc_hosts_dict fact
  set_fact:
    onpc_hosts_dict: >-
      {%- set sel = {} %}
      {%- for key, value in onpc_netboot_systems.items() %}
      {%-   if value.cardinality is defined and value.cardinality > 0 %}
      {%-     set count = value.cardinality %}
      {%-       for i in range(count) %}
      {%-         set name = key ~ '-' ~ i %}
      {%-         set hostname = name ~ '.' ~ onpc_infra_domain %}
      {%-         set host = {
                    'name': name,
                    'gateway': value.gateway | default('', true),
                    'name_servers': value.name_servers | default([], true),
                    'name_servers_search': value.name_servers_search | default([], true),
                    'profile': value.profile | default('default-centos-7-x86_64', true),
                    'comment': value.comment | default('', true),
                    'roles': value.roles | default([], true),
                    'metadata': value.metadata | default([], true),
                    'state': value.state | default('present', true),
                    'status': value.status | default('production', true),
                    'netboot': value.netboot | default(True, true),
                    'partitions': value.partitions | default({}, true),
                    'interfaces': value.interfaces | default({}, true) } %}
      {%-         set sel = sel.update({hostname: host}) %}
      {%-       endfor %}
      {%-    endif %}
      {%- endfor %}
      {{- sel }}


