---
# As per OSA documentation, firewalld on the deployment host should be disabled.
# See https://docs.openstack.org/project-deploy-guide/openstack-ansible/rocky/deploymenthost.html
- name: Disable firewalld (RedHat/CentOS)
  service:
    name: firewalld
    enabled: false
    masked: true
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Set iptables facts (Debian)
  set_fact:
    iptables_package: iptables-persistent
    iptables_service: netfilter-persistent
  when: (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 9) or (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 16)

- name: Set iptables facts (RedHat/CentOS)
  set_fact:
    iptables_package: iptables-services
    iptables_service: iptables
  when: ansible_os_family == "RedHat"

- name: Install iptables-persistent (Debian/Ubuntu)
  package:
    name: "{{ iptables_package }}"
    state: present

- name: Enable iptables
  service:
    name: "{{ iptables_service }}"
    enabled: true
    state: started
