---
- name: Change facts to use netfilter-persistent on Debian >= 9 or Ubuntu >= 16
  set_fact:
    iptables_save_command: "/usr/sbin/netfilter-persistent save"
    iptables_service: netfilter-persistent
  when: (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 9) or (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 16)

- name: Install iptables-persistent (Debian/Ubuntu)
  package:
    name: iptables-persistent
    state: present
  when: ansible_os_family == "Debian"

# As per OSA documentation, firewalld on the deployment host should be disabled.
# See https://docs.openstack.org/project-deploy-guide/openstack-ansible/rocky/deploymenthost.html
- name: Disable firewalld (RedHat/CentOS)
  service:
    name: firewalld
    enabled: false
    masked: true
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Install iptables-services (RedHat/CentOS)
  package:
    name: iptables-services
    state: present
  when: ansible_os_family == "RedHat"

- name: Enable iptables
  service:
    name: "{{ iptables_service }}"
    enabled: true
    state: started


