---
- name: Create flavors of nova VMs
  os_nova_flavor:
    endpoint_type: internal
    cloud: default
    state: present
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
    swap: "{{ item.swap }}"
    ephemeral: "{{ item.ephemeral }}"