---
- name: Create networks
  os_network:
    endpoint_type: internal
    cloud: default
    state: present
    name: "{{ item[0].name }}"
    shared: "{{ item[0].shared }}"
    external: "{{ item[0].external }}"
    onpc_external_network_type: "{{ item[0].network_type }}"
    provider_physical_network: "{{ item[0]].physical_network | default ('') }}"
  with_items: "{{ networks }}"

- name: Create subnets on networks
  os_subnet:
    endpoint_type: internal
    cloud: default
    state: present
    name: "{{ item[1].name }}"
    network_name: "{{ item[1].network_name }}"
    ip_version: "{{ item[1].ip_version }}"
    cidr: "{{ item[1].cidr }}"
    gateway_ip: "{{ item[1].gateway_ip }}"
    enable_dhcp: "{{ item[1].enable_dhcp }}"
    allocation_pool_start: "{{ item[1].allocation_pool_start }}"
    allocation_pool_end: "{{ item[1].allocation_pool_end }}"
    dns_nameservers: "{{ item[1].dns_nameservers | default([]) }}"
  with_items: "{{ subnets }}"
  
- name: Create a router on both public and private networks
  os_router:
    endpoint_type: internal
    cloud: default
    state: present
    name: "{{ router_name }}"
    network: "{{ provider_net_name }}"
    interfaces:
      - "{{ private_subnet_name }}"
  ignore_errors: yes  # will report error if this router already exists
  register: router_details

- name: Get list of security groups
  # Must use shell here because Ansible does not have os_security_group_facts module
  shell: "source openrc ; openstack security group list -f yaml | awk '/ID/ {print $2}'"
  args:
    executable: /bin/bash
  register: sec_groups

- name: Setup rules on all security groups
  os_security_group_rule:
    endpoint_type: internal
    cloud: default
    security_group: "{{ item[1] }}"
    protocol: "{{ item[0].protocol }}"
    direction: "{{ item[0].direction }}"
    port_range_min: "{{ item[0].port_min | default(-1) }}"
    port_range_max: "{{ item[0].port_max | default(-1) }}"
  with_nested:
    - "{{ security_group_rules }}"
    - "{{ sec_groups.stdout_lines }}"