---
- name: Setup master node
  hosts: localhost
  connection: local
  become: true
  become_user: root

  vars_files:
    - deployment.yml

  tasks:
    - debug: var=item
      loop: "{{ onpc_osa_nodes }}"
    - name: Ensure systems exists in Cobbler
      cobbler_system:
        host: localhost
        username: cobbler
        password: cobbler 
        name: "{{ item.hostname }}" 
        state: "{{ item.state }}"
        use_ssl: False
        properties:
          hostname: "{{ item.hostname }}"
          profile: osa-node-centos7 
          comment: "{{ item.comment }}"
          gateway: "{{ item.gateway }}"
          mgmt_classes: "{{ item.roles }}"
          ks_meta: "{{ item.metadata }}"
          name_servers: "{{ item.name_servers }}"
          name_servers_search: "{{ item.name_servers_search }}"
          netboot_enabled: "{{ item.netboot }}"
        interfaces:
          eth0:
            ipaddress: "{{ item.interfaces['eth0'].ip_address | default('') }}"
            ifgateway: "{{ item.interfaces['eth0'].if_gateway | default('') }}" 
            macaddress: "{{ item.interfaces['eth0'].mac_address | default('') }}"
            static: "{{ item.interfaces['eth0'].static | default(True) }}" 
            bondingopts: "{{ item.interfaces['eth0'].bondig_opts | default('') }}" 
            bridgeopts: "{{ item.interfaces['eth0'].bridge_opts | default('') }}" 
            dnsname: "{{ item.interfaces['eth0'].dns_name | default('') }}"
            interfacemaster: "{{ item.interfaces['eth0'].interface_master | default('') }}" 
            interfacetype: "{{ item.interfaces['eth0'].interface_type | default('') }}" 
            management: "{{ item.interfaces['eth0'].management | default(True) }}" 
            netmask: "{{ item.interfaces['eth0'].netmask | default('') }}" 
            staticroutes: "{{ item.interfaces['eth0'].static_routes | default([]) }}" 
      loop: "{{ onpc_osa_nodes }}"