---
# task file for installing and configuring cobbler on CentOS

- name: set selinux to permissive mode
  shell: setenforce 0
  args:
    executable: /bin/bash

- name: set selinux in permissive mode permanently
  lineinfile: dest=/etc/selinux/config regexp="^SELINUX=" line="SELINUX=permissive"

- name: install epel repo
  yum: name=epel-release state=present

# cobbler depends on PyYAML, createrepo, httpd, mod_wsgi, rsync, tftp-server and so on.
- name: Set cobbler package dependencies
  set_fact:
    cobbler_packages:
        - dhcp
        - pykickstart
        - createrepo
        - httpd
        - mkisofs
        - mod_wsgi
        - mod_ssl
        - python-cheetah
        - python-netaddr
        - python-simplejson
        - python-urlgrabber
        - PyYAML
        - rsync
        - syslinux
        - tftp-server
        - yum-utils
        - bind
        - bind-utils
        - fence-agents
        - cobbler

- name: install related packages
  yum:
    name: "{{ cobbler_packages }}"
    state: present
  
- name: generate crypted password
  shell: openssl passwd -1 {{ cobbler_default_password }}
  register: result
  failed_when: result.rc != 0

- name: set default cobbler password crypted
  set_fact:
    cobbler_default_password_crypted: "{{ result.stdout }}"

- name: template /etc/cobbler/settings
  template: src=etc/cobbler/settings.j2 dest=/etc/cobbler/settings backup=yes
  notify: restart cobblerd

- name: template /etc/cobbler/dhcp.template
  template: src=etc/cobbler/dhcp.template.j2 dest=/etc/cobbler/dhcp.template backup=yes

- name: change 'disable' to 'no' in /etc/xinetd.d/tftp
  lineinfile: dest=/etc/xinetd.d/tftp regexp="disable" line="disable = no" backup=yes

#----------------
# begin add snippets and kickstarts
#----------------
- name: add_public_key_for_root snippnet
  template: src=var/lib/cobbler/snippets/add_public_key_for_root.j2
            dest=/var/lib/cobbler/snippets/add_public_key_for_root
            backup=yes
  when: cobbler_root_public_keys is defined

- name: post_install_network_config_ignore_interface snippnet
  template: src=var/lib/cobbler/snippets/post_install_network_config_ignore_interface.j2
            dest=/var/lib/cobbler/snippets/post_install_network_config_ignore_interface
            backup=yes

- name: /var/lib/cobbler/kickstarts/centos7-customized-sda
  template: src=var/lib/cobbler/kickstarts/centos7-customized-sda.j2
            dest=/var/lib/cobbler/kickstarts/centos7-customized-sda.ks
            backup=yes

- name: /var/lib/cobbler/kickstarts/centos7-customized-vda
  template: src=var/lib/cobbler/kickstarts/centos7-customized-vda.j2
            dest=/var/lib/cobbler/kickstarts/centos7-customized-vda.ks
            backup=yes

- name: /var/lib/cobbler/kickstarts/centos7-osa_ceph-sda
  template: src=var/lib/cobbler/kickstarts/centos7-osa_ceph-sda.j2
            dest=/var/lib/cobbler/kickstarts/centos7-osa_ceph-sda.ks
            backup=yes

- name: /var/lib/cobbler/kickstarts/centos7-osa_compute-sda
  template: src=var/lib/cobbler/kickstarts/centos7-osa_compute-sda.j2
            dest=/var/lib/cobbler/kickstarts/centos7-osa_compute-sda.ks
            backup=yes

- name: /var/lib/cobbler/kickstarts/centos7-osa_infra-sda
  template: src=var/lib/cobbler/kickstarts/centos7-osa_infra-sda.j2
            dest=/var/lib/cobbler/kickstarts/centos7-osa_infra-sda.ks
            backup=yes

- name: /var/lib/cobbler/kickstarts/centos7-osa_storage-sda
  template: src=var/lib/cobbler/kickstarts/centos7-osa_storage-sda.j2
            dest=/var/lib/cobbler/kickstarts/centos7-osa_storage-sda.ks
            backup=yes

- name: /var/lib/cobbler/kickstarts/centos7-osa_default-sda
  template: src=var/lib/cobbler/kickstarts/centos7-osa_default-sda.j2
            dest=/var/lib/cobbler/kickstarts/centos7-osa_default-sda.ks
            backup=yes

- name: /var/lib/cobbler/kickstarts/centos7-osa_swift-sda
  template: src=var/lib/cobbler/kickstarts/centos7-osa_swift-sda.j2
            dest=/var/lib/cobbler/kickstarts/centos7-osa_swift-sda.ks
            backup=yes

# end add snippets and kickstarts

- name: start and enable service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rsyncd
    - tftp
    - httpd
    - cobblerd

- name: cobbler get-loaders
  shell: cobbler get-loaders
  changed_when: false


# cobbler-web
- name: install cobbler-web
  include: web.yml
  when: cobbler_install_web is defined and cobbler_install_web




