---
- name: Change facts to use netfilter-persistent on Debian >= 9 or Ubuntu >= 16
  set_fact:
    iptables_save_command: "/usr/sbin/netfilter-persistent save"
    iptables_service: netfilter-persistent
  when: (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 9) or (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 16)

- name: Install iptables-persistent (Debian/Ubuntu)
  package:
    name: iptables-persistent
    state: present
  when: ansible_os_family == "Debian"

- name: Install iptables-services (RedHat/CentOS)
  package:
    name: iptables-services
    state: present
  when: ansible_os_family == "RedHat"

- name: Enable iptables
  service:
    name: "{{ iptables_service }}"
    enabled: true
    state: started

- name: Enable TFTP ports
  shell: |
    "iptables -A INPUT -i {{ infra_master_interface }} -m state --state NEW -m tcp -p tcp --dport 69 -j ACCEPT"
    "iptables -A INPUT -i {{ infra_master_interface }} -m state --state NEW -m udp -p udp --dport 69 -j ACCEPT"
  args:
    executable: /bin/bash

- name: Enable HTTP ports
  shell: |
    "iptables -A INPUT -i {{ infra_master_interface }} -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT"
    "iptables -A INPUT -i {{ infra_master_interface }} -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT"
  args:
    executable: /bin/bash

- name: Enable Cobbler XML-RPC ports
  shell: |
    "iptables -A INPUT -i {{ infra_master_interface }} -m state --state NEW -m tcp -p udp --dport 25150 -j ACCEPT"
    "iptables -A INPUT -i {{ infra_master_interface }} -m state --state NEW -m tcp -p udp --dport 25151 -j ACCEPT"
  args:
    executable: /bin/bash

- name: Save rules
  shell: |
    iptables-save
  args:
    executable: /bin/bash