---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

osa_release: "18.1.0"
root_ssh_dir: "{{ root_dot_ssh_dir | default('/root/.ssh') }}"
osa_deploy_dir: "/etc/openstack_deploy"
dest_repo_dir: "/opt"
osa_user_conf_file: "{{ osa_deploy_dir }}/user_variables.yml"
onpc_deployment_model: "onpc-basic-model"
onpc_user_conf_file: "{{ osa_deploy_dir }}/user_onpc_variables.yml"
onpc_model_repo_dir: "{{ dest_repo_dir }}/{{ onpc-deployment-model }}"
region_controller: "maas"
region_domain: "opennext.local"
ip_prefix: ""

# The proxy is the deployment host when it is configured as the default
# gateway for the machines it manages. The proxy should work transparently
# on TCP port (default 3128). Otherwise machines will need to access the
# proxy on a specific host and port.
#
# proxy_host: "{{ region_controller }}.{{ region_domaine }}"
# proxy_port: "3128"

# proxy_env: {
#   'http_proxy': "http://{{ proxy_host }}:{{ proxy_port }}",
#   'https_proxy': "http://{{ proxy_host }}:{{ proxy_port }}",
#   'ftp_proxy': "http://{{ proxy_host }}:{{ proxy_port }}",
#   'no_proxy': 'localhost,127.0.0.1',
# }

region_subnets:
  - external:
    cidr: 172.31.0.0/24
    reserved:
      - "172.31.0.1,172.31.0.100"
  - provider:
    cidr: 172.32.0.0/24
    reserved:
      - "172.32.0.1,172.32.0.100"
  - management:
    cidr: 172.29.236.0/22
    reserved:
      - "172.29.236.1,172.29.236.100"
  - private:
    cidr: 172.29.240.0/22
    reserved:
      - "172.29.240.1,172.29.240.100"
  - storage:
    cidr: 172.29.244.0/22
    reserved:
      - "172.29.244.1,172.29.244.50"

internal_lb_vip_address: 172.29.236.100
external_lb_vip_address: 172.31.0.100
