---
component_skel:
  elasticsearch:
    belongs_to:
      - logging_all
  kibana:
    belongs_to:
      - logging_all
  fluentd:
    belongs_to:
      - logging_all
container_skel:
  logging_container:
    belongs_to:
      - logging_containers
    contains:
      - elasticsearch
      - kibana
      - fluentd
    properties:
      container_fs_size: 125G
physical_skel:
  logging_containers:
    belongs_to:
      - all_containers
  logging_hosts:
    belongs_to:
      - hosts