---
- name: Mask NTP service
  systemd:
    name: ntpd
    enabled: no
    masked: yes
    state: stopped
  ignore_errors: yes
- name: 'Manage the chrony service'
  service:
    name: '{{ chrony_service_name }}'
    enabled: '{{ chrony_service_enabled }}'
    state: '{{ chrony_service_state }}'
  tags: 'chrony-service'
