---
- name: Set Squid HTTP iptables rules
  iptables_raw:
    name: squid_http_rules
    backup: yes
    keep_unmanaged: no
    rules: |
      -A INPUT -i "{{ squid_http_interface }}" -p tcp --dport "{{ squid_http_port }}" -j ACCEPT
      -A INPUT -i "{{ squid_http_interface }}" -p udp --dport "{{ squid_http_port }}" -j ACCEPT
  
- name: Set Squid port redirect rule
  iptables_raw:
    name: squid_redirect_rules
    backup: yes
    keep_unmanaged: no
    table: nat
    rules: |
      -A PREROUTING -i "{{ squid_http_interface }}" -p tcp ! -d "{{ squid_http_bind }}" --dport 80 -j REDIRECT --to-port "{{ squid_http_port }}"