---
- name: Set iptables facts (Debian)
  set_fact:
    iptables_save_command: "netfilter-persistent save"
    iptables_service: netfilter-persistent
  when: (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 9) or (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 16)

- name: Set iptables facts (RedHat/CentOS)
  set_fact:
    iptables_save_command: "iptables-save"
    iptables_service: "iptables"
  when: ansible_os_family == "RedHat"

- name: Install iptables-persistent (Debian/Ubuntu)
  package:
    name: iptables-persistent
    state: present
  when: ansible_os_family == "Debian"

- name: Install iptables-services (RedHat/CentOS)
  package:
    name: iptables-services
    state: present
  when: ansible_os_family == "RedHat"

- name: Enable iptables
  service:
    name: "{{ iptables_service }}"
    enabled: true
    state: started

- name: Enable Squid ports
  shell: |
    iptables -A INPUT -i "{{ squid_http_interface }}" -p tcp --dport "{{ squid_http_port }}" -j ACCEPT
    iptables -A INPUT -i "{{ squid_http_interface }}" -p udp --dport "{{ squid_http_port }}" -j ACCEPT
  args:
    executable: /bin/bash

- name: Enable Squid port redirect
  shell: |
    iptables -A PREROUTING -t nat -i "{{ squid_http_interface }}" -p tcp ! -d "{{ squid_http_bind }}" --dport 80 -j REDIRECT --to-port "{{ squid_http_port }}"
  args:
    executable: /bin/bash
  when: "squid_transparent_proxy is defined and squid_transparent_proxy"

- name: Save rules
  shell: |
    "{{ iptables_save_command }}"
  args:
    executable: /bin/bash