---
# Copyright (c) 2019, Patrick Petit <patrick.michel.petit@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Check the ONPC deployment hosts
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"

  vars_files:
    - vars/main.yml

  vars:
    host_roles: "{{ onpc_valid_roles | intersect(group_names) | unique | list }}"
    managed_host: "{{ host_roles | length > 0 | ternary (True, False) }}"

  tasks:
    - name: Assert that the Ansible version meets requirements
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >-
          "You must upgrade Ansible version to 2.7 or greater (current version is {{ ansible_version.full }})"

    - name: Setup networking facts
      import_tasks: tasks/setup-networking-facts.yml
      tags: always

    - name: Check OSA networks
      include_tasks: tasks/check-osa-networks.yml
      vars:
        network: "{{ item.value }}"
      with_dict: "{{ onpc_osa_networks }}"
      when:
        - onpc_osa_networks_check | default(true) | bool
        - managed_host
      tags: check-osa-networks

    - name: Install host packages
      include_tasks: tasks/install-host-packages.yml
      when: managed_host
      tags: install-host-packages


    - name: Configure host kernel
      import_tasks: tasks/configure-host-kernel.yml
      when: managed_host
      tags: configure-host-kernel

## Note PP: Already done by kickstart during netboot process
#    - include_tasks: tasks/import-root-public-key.yml
#      vars:
#       public_key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
#      when: managed_host
#      tags: import-root-public-key

    - name: Install and configure Chrony
      include_role:
        name: roles/chrony
      vars:
        chrony_server: "{{ time_server_addr | default('pool.ntp.org') }} prefer iburst"
      when:
        - managed_host
      tags: configure-host-chrony