---
# Copyright (c) 2019, Patrick Petit <patrick.michel.petit@gmail.com>

#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install Cobbler
  hosts: localhost
  connection: local
  become: true
  become_user: root

  vars_files:
    - vars/main.yml
    - vars/users.yml
    - vars/networks.yml
    - vars/cobbler.yml

  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >-
          "You must upgrade Ansible version to 2.7 or greater (current version is {{ ansible_version.full }})"
    
    - name: Check for supported Operating System platforms
      assert:
        that:
          - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
        msg: >
          The only supported Linux distribution to install Cobbler is CentOS 7

    - name: Verify oncp_master_root_public_key is properly defined
      assert:
        that: "{{ oncp_master_root_public_key | length > 0 }}"
        msg: "user 'root' public key is undefined"

    - name: Set networking facts
      import_tasks: tasks/setup-networking-facts.yml
      tags: always

    - name: Create directory for ISOs download
      file:
        state: directory
        path: /var/tmp/isos

    - name: Check ISO not already downloaded
      stat:
        path: /var/tmp/isos/CentOS-7-x86_64-DVD-1810.iso
      register: result
      tags: always

    - name: Download distros ISOs
      get_url:
        url: "{{ item.url }}"
        dest: "/var/tmp/isos/{{ item.name }}"
        timeout: 600   # big files might take a while to download
        mode: 0440
      register: download_result
      until: download_result is succeeded
      retries: 5 
      delay: 15
      failed_when: download_result is failure
      with_items:
        - { name: CentOS-7-x86_64-DVD-1810.iso, url: "http://mirror.plusserver.com/centos/7.6.1810/isos/x86_64/CentOS-7-x86_64-DVD-1810.iso" }
      when: result.stat.exists == false
      tags: download-distros

  roles:
    - role: ../roles/cobbler
      cobbler_server: "{{ ansible_default_ipv4.address }}"
      cobbler_next_server: "{{ ansible_default_ipv4.address }}"
      cobbler_subnet: "{{ ansible_default_ipv4.network }}"
      cobbler_netmask: "{{ ansible_default_ipv4.netmask }}"
      cobbler_dynamic_bootp_start: "{{ ansible_default_ipv4.network | ipmath(cobbler_bootp_range_start) }}"
      cobbler_dynamic_bootp_end: "{{ ansible_default_ipv4.network | ipmath(cobbler_bootp_range_end) }}"
      cobbler_routers: "{{ ansible_default_ipv4.gateway }}"
      cobbler_subnet_mask: "{{ ansible_default_ipv4.netmask }}"
      tags: install-cobbler
  
  post_tasks:
    - name: Sync Cobbler database
      cobbler_sync:
        host: "{{ master_infra_addr }}"
        username: "{{ cobbler_user }}"
        password: "{{ cobbler_password }}"
        use_ssl: False
      run_once: yes
      register: result
      failed_when: result.failed
      tags: cobbler-sync