---
# Copyright (c) 2019, Patrick Petit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Register Cobbler profiles
  hosts: localhost
  become: true
  become_user: root
  connection: local

  vars_files:
    - vars/main.yml

  tasks:
    - name: Assert that the Ansible version meets requirements
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >-
          "You must upgrade Ansible version to 2.7 or greater (current version is {{ ansible_version.full }})"

    - include_tasks: tasks/setup-networking-facts.yml

    - include_tasks: tasks/register-cobbler-mgmt-classes.yml

    - name: Get cobbler profiles
      command: >
        cobbler profile list
      register: result
      failed_when: result.rc != 0
      tags: always

    - name: Set registered_profiles fact
      set_fact:
        registered_profiles: "{{ result.stdout_lines | map('trim') | list | default([]) }}"
      tags: always

    - name: Set profile_roles fact
      set_fact:
          profile_roles: "{{ (item.value.roles | intersect(infra_group)) | ternary((item.value.roles + ['infra']) | unique | list, item.value.roles | unique | list) }}"
      vars:
        infra_group: ['controller', 'network', 'haproxy', 'image']
      tags: always

    - include_tasks: tasks/register-cobbler-profile.yml
      vars:
        profile_name: "{{ item.key | lower }}"
      with_dict: "{{ onpc_netboot_profiles }}"
    
    - name: Sync Cobbler database
      command: >
        cobbler sync
      run_once: yes
      register: result
      failed_when: result.rc != 0
      tags: register-cobbler-profiles
