---
#
# Playbook to populate a newly deployed OpenStack cloud with some flavors, images, etc.
#
# Runs against the Utility container on infra1, relying on the clouds.yaml file
# left there by the OpenStack-Ansible playbooks to specify the API endpoint and
# auth parameters to use.
#
- name: Setup initial OpenStack configuration
  hosts: utility_all[0]
  become: true
  become_user: root
  environment: "{{ deployment_environment_variables | default({}) }}"

  vars_files:
    - vars/main.yml
    - vars/openstack-config.yml

  tasks:
  - name: Ensure python-shade library is present to run ansible os_xxx modules
    apt:
      name: python-shade
      state: present
    tags: always
  
  - name: Create user flavors
    include_tasks: tasks/create-flavor.yml
    with_items: "{{ vm_flavors }}"
  
  - name: Create user images
    include_tasks: tasks/create-image.yml
    with_items: "{{ images }}"
  
  - name: Create user networks
    include_tasks: tasks/create-network.yml
    with_items: "{{ networks }}"

  - name: Create user subnets
    include_tasks: tasks/create-subnet.yml
    with_items: "{{ subnets }}"

  - name: Create user routers
    import_tasks: tasks/create-router.yml

  - name: Create user security group
    import_tasks: tasks/create-security-group.yml

