---
# Copyright (c) 2018, OpenNext SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 
# In order to import a distribution, you will need a DVD ISO for your
# distribution. NOTE: You must use a full DVD, and not a "Live CD" ISO.
# For this example, we'll be using the CentOS 7 x86_64 ISO, available
# for download here.
# http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-DVD-1810.iso
#
# Once this file is downloaded, mount it somewhere:
#
# $ mount -t iso9660 -o loop,ro /path/to/isos/CentOS-7-x86_64-DVD-1810.iso /mnt

- name: Setup Cobbler server
  hosts: localhost
  connection: local
  become: true
  become_user: root

  vars_files:
    - vars/main.yml
    - vars/networks.yml
  
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >-
          "You must upgrade Ansible version to 2.7 or greater (current version is {{ ansible_version.full }})"
    
    - name: Set common facts
      include_tasks: tasks/setup-common-facts.yml
      tags: setup-common-facts

  roles:
    - role: ../roles/squid
      squid_acl_localnet:
        - "{{ management_network }}"
        - "{{ infra_network }}"
      squid_pri_domain_name: "{{ onpc_infra_domain }}"
      squid_transparent_proxy: "{{ onpc_transparent_proxy }}"
      squid_transparent_proxy_ferm: "{{ onpc_transparent_proxy | ternary(True, False) }}"
      squid_http_port: "{{ onpc_proxy_port }}"
      squid_http_bind: "{{ infra_master_address }}"
      when: onpc_limited_connectivity